version: '3'

services:
  fast_api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
    - "8000:8500"
    depends_on:
      - rabbit
    restart: always
  rabbit:
    image: rabbitmq
    restart: always
  reciever:
    build:
      context: ./reciever
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    restart: always